### ISSUE TITLE
Config file contains entries needed for both CM and CD servers

### ISSUE THREAD

**Issue by dschoenberg** [iamandycohen/UrlRewrite#10]
During the server installation process it would be nice if the URL Rewrite module's config settings were broken up into two different config files.  Ideally, one of the configuration files would contain all of the settings that should not be present on the content delivery servers.  This would allow the person doing the installation to easily disable one file for the installation, rather than commenting out and managing different sections of one file.

**Comment by iamandycohen** [comment]
This has been done.
