### ISSUE TITLE
Could we make the "Simple Redirects" within Sitecore always use 301 Redirect statuscode?

### ISSUE THREAD

**Issue by HorizontalDevs** [iamandycohen/UrlRewrite#12]
Could we make the "Simple Redirects" within Sitecore always use 301 Redirect statuscode? How much effort would that take? I tested one of the redirects I had already set up for one of the website, and it is using a 301 AND 302 redirect, for some reason. We really want all of them to just use 301 redirects.

We know that Inbound rules provide this functionality. But the inbound rules are much more complicated than I think they need to be, with multiple steps to get up one redirect (i.e. set up the Pattern Match, then the Redirect). Also, most of the time, we won't want to be setting up a Pattern Match, but a specific exact match. The pattern matching admin screen is pretty confusing and overwhelming for the average content author. I want them to just be able to set up the Simple Redirects and have it use a 301 redirect.

**Comment by iamandycohen** [comment]
I don't think I would like to implement this.  If you want to customize your version, you could change the standard values on the template to be a 301.
