### ISSUE TITLE
Can't find Redirect Folder after installing

### ISSUE THREAD

**Issue by dhylde17** [iamandycohen/UrlRewrite#15]
Hello
I've installed the module on SiteCore 7.2
After installing this package, I cannot find the Redirect Folder in sitecore/templates/Modules/UrlRewrite/Templates/Redirect Folder.

Did I miss something?

Best regards

**Comment by iamandycohen** [comment]
Sorry.. the instructions are outdated.  The template has been moved to "/sitecore/templates/User Defined/UrlRewrite/Templates/Folders/Redirect Folder"
