### ISSUE TITLE
Can we match url with request uri or other elements?

### ISSUE THREAD

**Issue by nkachhla** [iamandycohen/UrlRewrite#21]
Hi,

I've just tried to match the bits of the url after the http_host but it doesnt seem to match.

I've using the advanced condition and used condition input string {REQUEST_URI} to match. However, it doesnt seem to work. Is there any way for this to work?

Thanks in advance,

Neel

**Comment by iamandycohen** [comment]
Can you provide an example url and a regular expression you are using to
match?

**Comment by nkachhla** [comment]
Hi Andy,

Thanks for your quick response. The url I am trying to match is something like

http://www.testwebsite.com/inspiration
or
http://www.testwebsite.com/inspiration/somethingelse

For this, I am creating an inbound rule with fields "matching patterns", "Regular Exprressions" and pattern `(.*)`set.
My advanced condition has condition input string `{REQUEST_URI}` with the curly brackets and the pattern it is looking for is `^inspiration(.*)?$` and it is a simple external redirect.

Thanks,

Neel

**Comment by iamandycohen** [comment]
REQUEST_URI would match on the entire URL, which would include the http://www.testwebsite.com/inspiration etc...  The easiest option I can see:

** Use Pattern of ^inspiration(.*)?$ without any condition
