### ISSUE TITLE
Issue with languages in URL

### ISSUE THREAD

**Issue by nhorvat123** [iamandycohen/UrlRewrite#29]
I am trying to put in a redirect with the pattern of "^old/page1$" so that I can redirect http://www.website.com/en/old/page1 to http://www.website.com/en/new/page2. 

When I set my return URL to "http://{HTTP_HOST}/new/page2", I am redirected to http://www.website.com/new/page2 instead of http://www.website.com/en/new/page2. 

I am working on a multilingual site (on Sitecore version 7.2), so I am not able to hard-code the return URL to http://www.website.com/en/new/page2. 

Is there any way to carry over the language from the original URL? When I put the language into the pattern to match with the URL, it doesn't work.

**Comment by onbas** [comment]
Sitecore removes the language from the URL ("Languages.AlwaysStripLanguage"). That's probably the reason why there is no match in patterns where language the is included.
This issue is closed without comments. I was wondering how you solved it?

**Comment by iamandycohen** [comment]
I don't think this was solved.  If there is interest, I can add it as a new feature.  However,  all of my templates are shared and don't worry about language.  How would you envision this implementation?
