### ISSUE TITLE
Is it possible to redirect a media library item? 

### ISSUE THREAD

**Issue by JawadS** [iamandycohen/UrlRewrite#45]
We've tried media library links in a simple redirect and it doesn't seem to work. 

Like the below: 

![image](https://user-images.githubusercontent.com/8505245/48894190-07bada00-ee3a-11e8-91a5-4d11eeefa6c6.png)

Is there any other way to redirect media library items?

**Comment by felipebsouza** [comment]
I'm stuck on the same problem. Have you found a solution for that @JawadS?

Is there a way to do that @iamandycohen?

**Comment by iamandycohen** [comment]
@felipebsouza Can you contact me at iamandycohen@gmail.com or andy.cohen@sitecore.com?

**Comment by iamandycohen** [comment]
Oh... I know this is really old, but here was the solution posted a few years ago...  https://horizontal.blog/2014/12/19/sitecore-url-rewrite-module-for-static-file-extensions/
