### ISSUE TITLE
Add an OSS license

### ISSUE THREAD

**Issue by richardszalay** [iamandycohen/UrlRewrite#50]
Any chance you could add an OSS license (eg. MIT / Apache2) to the project? Unlicensed code is a bit tricky from a legal perspective, and many clients legal teams might take issue with it.

**Comment by RussHelfand** [comment]
I second the request from Richard Szalay: please consider adding a license (e.g., MIT) to the project. This will make it much, much easier for others to use your terrific work. Thanks!

**Comment by iamandycohen** [comment]
License add in #54
