### ISSUE TITLE
How to use this module in a multi site (multi domain) setup?

### ISSUE THREAD

**Issue by JawadS** [iamandycohen/UrlRewrite#53]
We are running SXP 9.0.1 PaaS with multiple sites setup in the same solution. with three different domains. 

The module has been installed and it was running fine, we were able to create different types of redirects. 

However we realised if you have a redirect setup within the solution it's basically affecting other sites as well, which we don't want to happen. 

Is there a way to make the redirects site specific?

**Comment by iamandycohen** [comment]
Yes it does. But this hasn't been updated in a long time. The site specific settings have a special field type that look at the site definitions to populate the dropdown - I don't think this will work with SXA virtual sites - but I don't know. On the root of a redirect folder, on the Content tab is a Site Name Restriction field, where you can choose the site.

**Comment by jsabra1** [comment]
Hey Andy, Really appreciate your quick response. That actually worked like a charm! Thank you. We're not using SXA.
