### ISSUE TITLE
Unpublished item causes Sitecore errors

### ISSUE THREAD

**Issue by dschoenberg** [iamandycohen/UrlRewrite#9]
After installing the URLRewrite module the follow error was being written to the logs:
Exception: System.InvalidOperationException
Message: Root item  /sitecore/system/Modules/Url Rewrite/Reporting is not defined for index UrlRewriteReporting in web database
Source: Sitecore.Kernel
   at Sitecore.Diagnostics.Assert.IsNotNull(Object value, String message)
   at Sitecore.Search.Crawlers.DatabaseCrawler.Initialize(Index index)
   at Sitecore.Search.Index.AddCrawler(ICrawler crawler)

This can be resolved by publishing all related URL Rewrite items, however that is not defined in the installation steps and it may have been blocking the installation of another package.

**Comment by iamandycohen** [comment]
This is no longer an issue
